### ISSUE TITLE
OrderedRegistry's Serialization not implemented

### ISSUE THREAD

**Issue by MeucheRoume** [CoolLibs/reg#3]
Even when adding a specialisation for serialize function, we triggered a static assert from cereal : 
`cereal could not find any input serialization functions for the provided type and archive combination.`

After different tries, I also notice the same error with serialization with Registry, I had this assert : 
`Types must either have a serialize function, load/save pair, or load_minimal/save_minimal pair (you may not mix these).`

**Comment by JulesFouchy** [comment]
RTFM
